development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: postgres
  password: masterkey

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: postgres
  password: masterkey

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: postgres
  password: masterkey